#!/bin/sh

export PATH

# devtmpfs does not get automounted for initramfs
mount -t devtmpfs devtmpfs /dev

mount /run
mkdir -p /run/lock
mount /proc
mount /sys

# Start mdev if available in BusyBox
if [ -x /sbin/mdev ]; then
    mdev -s
fi

init='/bin/busybox init'
exec $init
